DATASETS:
  TRAIN: ("ADE_base_train", )
  PRECOMPUTED_PROPOSAL_TOPK_TRAIN: 100
  PRECOMPUTED_PROPOSAL_TOPK_TEST: 100

SOLVER:
  IMS_PER_BATCH: 8
  MAX_ITER: 15600
  CHECKPOINT_PERIOD: 2600
  BASE_LR: 0.1
  WEIGHT_DECAY: 0.0001
  LR_SCHEDULER_NAME: "WarmupCosineLR"
  WARMUP_FACTOR: 0.0001
  WARMUP_ITERS: 2600

MODEL:
  PROPOSAL_GENERATOR:
    NAME: "PrecomputedProposals"

  BACKBONE:
    NAME: "build_my_resnet_backbone"
    FREEZE_AT: 0
  RESNETS:
    DEPTH: 18
    RES2_OUT_CHANNELS: 64
    OUT_FEATURES: ["res5"]

  ROI_HEADS:
    NAME: "ROI_CLS"
    IN_FEATURES: ["res5"]
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 3

OUTPUT_DIR: "./output/baseline/base_train"